name: Deploy (DEV)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
          
  deploy-to-dev:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build commit image
        run: sudo docker build --build-arg BUILD_ENV="dev" -t amisdary/personal-website-dev:${{ github.sha }} .
    
      - name: Tag commit image as latest
        run: sudo docker tag amisdary/personal-website-dev:${{ github.sha }} amisdary/personal-website-dev:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ variables.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub 
        run: |
          docker push amisdary/personal-website-dev:${{ github.sha }}
          docker push amisdary/personal-website-dev:latest 

      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.DROPLET_IP}}
          username: deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            docker pull amisdary/personal-website-dev:latest
            docker compose up -d --remove-orphans personal-website-dev