name: Deploy (PROD)

on:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test
          
  deploy-to-prod:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build commit image
        run: sudo docker build --build-arg BUILD_ENV="production" -t amisdary/personal-website:${{ github.sha }} .
    
      - name: Tag commit image as latest
        run: sudo docker tag amisdary/personal-website:${{ github.sha }} amisdary/personal-website:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub 
        run: |
          docker push amisdary/personal-website:${{ github.sha }}
          docker push amisdary/personal-website:latest 

      - name: Copy docker-compose.yml to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: deploy
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/personal-website"

      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.DROPLET_IP}}
          username: deploy
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            docker pull amisdary/personal-website:latest
            docker compose up -d --remove-orphans personal-website